[package]
name = "vmm_vhost"
version = "0.1.0"
keywords = ["vhost", "vhost-user", "virtio", "vdpa"]
description = "a pure rust library for vdpa, vhost and vhost-user"
authors = ["Liu Jiang <gerry@linux.alibaba.com>"]
repository = "https://github.com/rust-vmm/vhost"
documentation = "https://docs.rs/vhost"
readme = "README.md"
license = "Apache-2.0 or BSD-3-Clause"
edition = "2021"

[features]
default = []
vmm = []
device = []
vfio-device = []

[dependencies]
anyhow = "*"
base = { path = "../../base" }
bitflags = "1.3.2"
cfg-if = "1.0.0"
data_model = { path = "../../common/data_model" }
libc = "0.2.139"
remain = "0.2.6"
tempfile = "3.3.0"
thiserror = { version = "1.0.20" }

[target.'cfg(windows)'.dependencies]
serde = "1.0.152"
serde_json = "1.0.93"
